export const LOGIN_REQUEST = 'PROFILE/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'PROFILE/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'PROFILE/LOGIN_FAIL';
export const LOGIN_CANCEL = 'PROFILE/LOGIN_CANCEL';

export const REGISTRATION_REQUEST = 'PROFILE/REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'PROFILE/REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'PROFILE/REGISTRATION_FAIL';
export const REGISTRATION_CANCEL = 'PROFILE/REGISTRATION_CANCEL';

export const GET_USER_INFO_REQUEST = 'PROFILE/GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'PROFILE/GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'PROFILE/GET_USER_INFO_FAIL';
export const GET_USER_INFO_CANCEL = 'PROFILE/GET_USER_INFO_CANCEL';

export const LOGOUT = 'PROFILE/LOGOUT';